# Generated by Django 5.1 on 2024-11-07 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('tin_chi', models.IntegerField()),
                ('hoc_phi', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mo_ta', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DangKyMonHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('huy_dang_ky', models.BooleanField(default=False)),
                ('mon_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dkymonhoc.monhoc')),
            ],
        ),
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=150)),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=4)),
                ('ngay_sinh', models.DateField()),
                ('mon_hoc', models.ManyToManyField(through='dkymonhoc.DangKyMonHoc', to='dkymonhoc.monhoc')),
                ('tai_khoan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dangkymonhoc',
            name='sinh_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dkymonhoc.sinhvien'),
        ),
    ]
